//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namordnik.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Characteristic
    {
        public int ID { get; set; }
        public int Length { get; set; }
        public int Width { get; set; }
        public int Heigth { get; set; }
        public int ShippingWeight { get; set; }
        public int WeightWithoutPackaging { get; set; }
        public string Certificate { get; set; }
        public string Standard { get; set; }
    }
}
