//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Namordnik.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Article { get; set; }
        public string TitleProduct { get; set; }
        public double MinimumCostForAnAgent { get; set; }
        public string Picture { get; set; }
        public int TypeProductID { get; set; }
        public int NumberOfPeopleForProduction { get; set; }
        public int WorkshopNumberForPeoduct { get; set; }
        public Nullable<int> CharacteristicID { get; set; }
    }
}
